- app/craco.config.js
- app/package.json
- yarn.lock
Add craco to inject additional config into the create-react-app build script and downgrade react-scripts to include polyfills required in tests
> Fix react build

- README.md
- Fixed link
- Changed Copyright to finos
> Onboarding - minor edits

- whitesource.config
Attempt at ignoring dev dependencies
> Ignoring dev deps

- mock-app/index.html
- tests/src/test/fdc3.open.ts
This uses context / broadcast to validate that the app is opened - it also sends back the received context.
relates to #18
> added validation to ensure the app is opened and receives context

- tests/src/test/fdc3.findIntent.ts
- tests/src/test/fdc3.findIntentsByContext.ts
- tests/src/test/fdc3.open.ts
- tests/src/test/fdc3.raiseIntent.ts
- tests/src/test/fdc3.raiseIntentForContext.ts
Changed open test to check if return is an object with the correct message
Issue #53
> Check API methods return Error with message

- mock/README.md
- tests/src/test/fdc3.findIntent.ts
- tests/src/test/fdc3.findIntentsByContext.ts
- tests/src/test/fdc3.open.ts
- tests/src/test/fdc3.raiseIntent.ts
- tests/src/test/fdc3.raiseIntentForContext.ts
Tests link to web FDC3 docs when possible
Screenshot:
> Add mock app and test documentation

- mock/channels/index.html
- tests/src/constants.ts
- tests/src/test/fdc3.broadcast.ts
One additional test created for #17  this issue following Kris' last comment:
https://github.com/finos/FDC3-conformance-framework/issues/17
> 17 App Channel tests

- mock/channels/channelService.js
- mock/channels/index.html
- tests/src/constants.ts
- tests/src/test/fdc3.broadcast.ts
Code refactoring to make the channels mock app index.html script more readable
> Channels mock app code refactor

- mock/fdc3-app-config-examples/finsemble.app-d-snippet.txt
- tests/src/apiDocuments.ts
- tests/src/test/fdc3.addContextListener.ts
- tests/src/test/fdc3.addIntentListener.ts
- tests/src/test/fdc3.broadcast.ts
- tests/src/test/fdc3.findIntent.ts
- tests/src/test/fdc3.findIntentsByContext.ts
- tests/src/test/fdc3.getCurrentChannel.ts
- tests/src/test/fdc3.getInfo.ts
- tests/src/test/fdc3.getOrCreateChannel.ts
- tests/src/test/fdc3.getSystemChannels.ts
- tests/src/test/fdc3.leaveCurrentChannel.ts
- tests/src/test/fdc3.open.ts
- tests/src/test/fdc3.raiseIntent.ts
- tests/src/test/fdc3.raiseIntentForContext.ts
Added link to docs in failed test, couple extra tests added
> Add documentation to failed test output

- tests/src/test/fdc3.broadcast.ts
- tests/src/test/fdc3.open.ts
- tests/src/test/fdc3.raiseIntent.ts
This PR addresses all issues from [#72 ](https://github.com/finos/FDC3-conformance-framework/issues/72)
> Fix incorrect test definitions

- .github/workflows/static.yml
Runs the build then deploys the entire repo contents to gh-pages. This is a bit messy, but works for now.
Here's the app: https://colineberhardt.github.io/FDC3-conformance-framework-1/app/
And an example mock: https://colineberhardt.github.io/FDC3-conformance-framework-1/mock/general/
> Added a GitHub action that deploys to Github Pages

- tests/src/test/fdc3.broadcast.ts
- tests/src/test/fdc3.findIntent.ts
- tests/src/test/fdc3.findIntentsByContext.ts
- tests/src/test/fdc3.getCurrentChannel.ts
- tests/src/test/fdc3.open.ts
- tests/src/test/fdc3.raiseIntent.ts
Reconciled with https://github.com/finos/FDC3/pull/848/files?short_path=f67cb64#diff-f67cb64803ca89a0d6c838830806d9d3f0cec2fdd432997dcfde8a66191b06dc
> Labelled all conformance tests

- tests/src/test/v1.2/advanced/fdc3.broadcast.ts
addresses the changes and issues raised [here](https://github.com/finos/FDC3/pull/848):
- remove ACBasicUsage3
- ammend ACContextHistoryMultiple
> Make required broadcast test changes

- mock/channels/index.html
- tests/src/test/v1.2/advanced/fdc3.broadcast.ts
- tests/src/test/v1.2/advanced/fdc3.findIntent.ts
- tests/src/test/v1.2/advanced/fdc3.findIntentsByContext.ts
- tests/src/test/v1.2/advanced/fdc3.open.ts
- tests/src/test/v1.2/advanced/fdc3.raiseIntent.ts
- tests/src/test/v1.2/basic/fdc3.addContextListener.ts
- tests/src/test/v1.2/basic/fdc3.addIntentListener.ts
- tests/src/test/v1.2/basic/fdc3.getCurrentChannel.ts
- tests/src/test/v1.2/basic/fdc3.getInfo.ts
- tests/src/test/v1.2/basic/fdc3.getOrCreateChannel.ts
- tests/src/test/v1.2/basic/fdc3.getSystemChannels.ts
- tests/src/test/v1.2/basic/fdc3.joinChannel.ts
- tests/src/test/v1.2/basic/fdc3.leaveCurrentChannel.ts
- tests/src/test/v1.2/basic/fdc3.raiseIntentForContext.ts
- tests/src/test/v2.0/advanced/fdc3.broadcast.ts
- tests/src/test/v2.0/advanced/fdc3.findInstances.ts
- tests/src/test/v2.0/advanced/fdc3.getAppMetadata.ts
- tests/src/test/v2.0/basic/fdc3.getInfo.ts
- tests/src/test/v2.0/basic/fdc3.getUserChannels.ts
- fixes an issue we had with the way the fdc3 API was being cast to the relevant `DesktopAgent`
- updated v2 broadcast and getInfo tests (in progress)
> Fixes issue with the way the fdc3 api was being cast to DesktopAgent & latest update for ongoing v2 broadcast/getInfo tests

- mock/general/index.html
- mock/intent-b/index.html
- mock/intent-c/index.html
- tests/src/test/v1.2/advanced/fdc3.findIntent.ts
- tests/src/test/v1.2/advanced/fdc3.findIntentsByContext.ts
- tests/src/test/v1.2/advanced/fdc3.open.ts
- tests/src/test/v1.2/basic/fdc3.getSystemChannels.ts
- tests/src/test/v1.2/basic/fdc3.joinChannel.ts
- tests/src/test/v1.2/basic/fdc3.raiseIntentForContext.ts
- updated v1.2 open tests (from Oli)
- minor amendments to test reference tags
- removed duplicate test
> v1.2 open tests & other minor ammendments

- mock/v1.2/intent-c/index.html
- fixes a bug that can cause a couple of the open tests to fail
> Fix intermittent open test error

- mock/v1.2/channels/lib/channelService-1_2.js
- mock/v1.2/lib/constants.js
- mock/v2.0/channels/lib/channelService-2_0.js
- mock/v2.0/lib/constants.js
- tests/src/test/v1.2/advanced/fdc3.broadcast.ts
- tests/src/test/v1.2/basic/fdc3.joinChannel.ts
- tests/src/test/v2.0/basic/fdc3.joinUserChannel.ts
- Fixes the channel id issue when testing broadcast tests with Glu42
> fix channel id issue with Glu42 in broadcast tests

- src/test/v1.2/advanced/fdc3.open.ts
> Remove malformed context from open tests

- README.md
A few changes to the main readme
> Added release version, link to conformance on main site

- options/connectifi-adapter.js
changed the module include to point to LTS agent.  All tests passing.
> change connectifi agent module to always point to latest version

- src/test/common/fdc3.open.ts
- src/test/v1.2/fdc3-1_2-utils.ts
…WithWrongContext screwing everythign else up
> 1.2 Regressions

- src/test/v1.2/basic/fdc3.basic.ts
RI1/RI2 intermittent failure in sail
> Fixing sail regression
