finos/FDC3-conformance-framework

- .gitignore
- mock/channels/index.css
- mock/channels/index.html
- mock/package.json
- tests/app-d-snippet.txt
- tests/src/constants.ts
- tests/src/test/fdc3.addContextListener.ts
- tests/src/test/fdc3.broadcast.ts
- tests/src/test/fdc3.getCurrentChannel.ts
- tests/src/test/fdc3.joinChannel.ts
This pull request implements the test cases for "System / User Channels Test Cases" (#16 )
**Notes**
- After having a chat with AJ I decided to scrap the two test cases that target v1.2 and v2.0 respectively. I'm not sure there is a way to pass an invalid Context object to the broadcast() function without casting it to `any`
- Two of the tests fail. The listeners receive context when they shouldn't. I believe the tests are correct but feel free to flag them if you spot anything wrong with them.
> #16 - System / User Channels Test Cases

- tests/src/constants.ts
- tests/src/test/fdc3.broadcast.ts
**Improved error reporting for failed channel tests:**
- Added step by step guide on how to reproduce failed broadcast tests
- Added link to documentation in failed tests
Example:
**In addition:**
- Fixed a bug whereby some failed tests were being duplicated
- Fix: some context listeners were using a context type filter when they shouldn't have been
> Improved error reporting for failed channel tests

- tests/src/test/fdc3.broadcast.ts
An app channel test was relying on the same behavior as user channels in an area where they differ. 
App channels do not auto-broadcast current context to apps that retrieve them and add a context listener. Instead, they have a `getCurrentContext` function which should return either the most recent context or (if a type is specified) the most recent context of that type. This PR replaces teh incorrect test with two tests for the `getCurrentContext` function.
This PR also corrects language used in comments and test output (you don't join app channels, you retrieve them)
> Correcting app channels tests for current context

- mock/channels/channelService.js
- mock/channels/index.html
- mock/general/index.html
- mock/intent-a/index.html
- mock/intent-b/index.html
- mock/intent-c/index.html
- mock/mock-functions.js
- tests/src/constants.ts
- tests/src/test/fdc3.broadcast.ts
- tests/src/test/fdc3.open.ts
- tests/src/test/fdc3.raiseIntent.ts
This is a pull request that addresses the following points from issue [#74](https://github.com/finos/FDC3-conformance-framework/issues/74):
-3) Some tests are hard to grok:
>Much of the Channel tests' code has been refactored for improved test readability and efficiency. 
-4) Wait times and total runtime:
> Timeouts now get cancelled if the promise above resolves first.
> Removed wait times wherever possible.
> Overall runtime speed is much faster.
-5) Window closing:
>The timeout that waits for the window to close should have been removed and was left there by mistake. This has now been fixed for all tests.
>All tests now use `window.close` to close the mock app windows
This pull request also addresses issue [#83](https://github.com/finos/FDC3-conformance-framework/issues/83):
- All …
> Channel tests refactor & improved test efficiency

- tests/src/test/v1.2/advanced/fdc3.broadcast.ts
- tests/src/test/v1.2/basic/fdc3.addContextListener.ts
- tests/src/test/v2.0/advanced/fdc3.broadcast.ts
We've bit an issue with the `Assert.isObject` assertion used to validate listeners - as per the assertions docs it does not return true for subclassed objects, which we use in our 2.0 implementation - where a simpler `typeof` based check is fine (in fact in most places this check is redundant as the next check is to look for a property of the object, e.g. listener.unsubscribe).
This PR swaps out the assertion for typeof based check and an Assert.isTrue assertion.
> Fix object assertions

- mock/intent-a/index.html
- mock/intent-b/index.html
- mock/intent-c/index.html
- tests/src/constants.ts
- tests/src/test/v1.2/advanced/fdc3.broadcast.ts
- tests/src/test/v1.2/advanced/fdc3.open.ts
- tests/src/test/v1.2/advanced/fdc3.raiseIntent.ts
- tests/src/test/v2.0/advanced/fdc3.broadcast.ts
- tests/src/test/v2.0/advanced/fdc3.findInstances.ts
- tests/src/test/v2.0/advanced/fdc3.getAppMetadata.ts
- tests/src/test/v2.0/basic/fdc3.getInfo.ts
- tests/src/utils.ts
While testing, we had a very occasional failure in raiseIntent tests caused by a race between window closing and test execution. This is fixed by adding a small wait time after each window close.
While making that change we applied a few other code improvements:
- Moved duplicated wait functions to a util file so that they are not redefined in every test,
- Made timeouts local to functions that use them to avoid clashes between them/accidental overwrites or clears, 
- Removed redundant return statements from event handlers (noop if last statement in the function)
- Removed Promise constructor where not needed (antipattern, just use the async keyword)
- Added short wait times on window close to reduce chance or race conditions in tests/unstable results.
There are likely other re-used …
> Fix antipatterns and local timer code

- mock/general/index.html
- mock/intent-a/index.html
- mock/intent-b/index.html
- mock/intent-c/index.html
- mock/mock-functions.js
- to avoid confusion, I've split `closeWindowOnCompletion` into two so that `await` is used in front of fdc3 API calls when it should, and isn't used when it shouldn't
- also added sleep function after broadcasting to give mock apps time to close
- removed unused listener
> When closing mock app windows, await fdc3 api calls/or not depending on the version retrieved

- package-lock.json
- package.json
- src/constants.ts
- src/mock/v1.2/channelService-1_2.ts
- src/test/v1.2/advanced/fdc3.open.ts
This PR addresses a problem in the open tests, where they should fail on an implementation defined timeout (FDC3 does not define the timeout only the error that should be thrown). As some apps in financial services can take an age to start-up/bootstrap themselves this is sometimes quite a long timeout. Further, we need messaging to explain it on a failure as if a DA uses a longer timeout the test will fail, but the DA may still be exhibiting correct behavior.
The PR also makes the package.json script work cross-platform. This was only tested on Windows PowerShell however (but has a much better chance of working elsewhere than the existing scripts) - please test!
Finally, please note that the timeout changes will be needed in the 2.0 implementation for both the open tests and RaiseIntent …
> Timeout and other fixes

- src/constants.ts
Finsemble used a 70sec timeout when determining whether an app will (ever) add its context listener. Extend test timeouts to exceed this to avoid custom configuration when testing.
> Extend timeout used in open tests to 75 secs

- src/constants.ts
- src/test/v1.2/basic/fdc3.joinChannel.ts
Removes a check from BasicJC1 that was based on an app broadcasting a context and then receiving it back - the Standard recommends that this is prevented 
> Channel implementations SHOULD ensure that context messages broadcast by an application on a channel are not delivered back to that same application if they are also listening on the channel.
https://fdc3.finos.org/docs/api/spec#types-of-channel
As the advanced System Channel checks already cover broadcast to the channel and receipt by other apps this check is not needed (and went beyond test definition anyway)
Based on PR #131 which should be merged first
> Remove incorrect check from BasicJC1

- directories/finsemble.app-d-snippet.txt
- src/constants.ts
- src/mock/v1.2/intent-b.ts
- src/mock/v1.2/mock-functions.ts
- src/test/v1.2/basic/fdc3.joinChannel.ts
Corrects a small error in the Intent App B implementation that was breaking the execution of SingleResolve1.
Also: 
- adds some log messages to mock-functions to ease future debugging
- updates FInsemble config snippet to show apps launched (rather than hide) - this change was made previously but has been reverted at some point
This PR builds on:
https://github.com/finos/FDC3-conformance-framework/pull/131
https://github.com/finos/FDC3-conformance-framework/pull/132
which should be merged first
> Correct error in intent-app-b

- directories/local-conformance-1_2.v2.json
- src/constants.ts
- src/test/common/channel-control.ts
- src/test/common/fdc3.app-channels.ts
- src/test/common/fdc3.user-channels.ts
- src/test/v1.2/advanced/channels-support-1.2.ts
- src/test/v2.0/advanced/channels-support-2.0.ts
- Adds extra parameter to 
```
setupAndValidateListener1(channel: X | null, listenContextType: string | null, expectedContextType: string | null, errorMessage: string, onComplete: (ctx: Y) => void): void | Promise<void>;
setupAndValidateListener2(channel: X | null, listenContextType: string | null, expectedContextType: string | null, errorMessage: string, onComplete: (ctx: Y) => void): void | Promise<void>;
```
to allow for different listen/expected
- Adds extra wait time so that we are giving enough time before deciding that we haven't seen a context.
- Removes     `validateContextIsNotReceived` since this was incorrectly implemented and added extra listeners, and the functionality is taken care of by the above two bullets.
> App channel fixes rm

- src/test/v1.2/basic/fdc3.joinChannel.ts
Simplifying the test for checking that joined channel is correct as a full deep compare is not needed.
> ID only check for BasicJC2

- src/mock/v1.2/channelService-1_2.ts
- src/test/common/channel-control.ts
- src/test/common/fdc3.user-channels.ts
- src/test/v1.2/advanced/channels-support-1.2.ts
Add `contextId` to tests to avoid falsy test results due to replaying of addContextListener's callback with previously broadcasted data
> User channels context

- src/test/common/fdc3.user-channels.ts
This PR addresses this issue: https://github.com/finos/FDC3-conformance-framework/issues/169
**Changes:**
- `UCFilteredUsageJoin` test was already there, it just had the wrong title which I've now amended
- `UCFilteredUsageNoJoin` is a duplicate of `BasicCH2` so we need to remove `UCFilteredUsageNoJoin` from the test definitions
- Bug fix: UCFilteredUsageJoin was timing out when run as a single test due to the after each waiting for the mock app window to close. This particular test does not open a mock app and this was causing the test to timeout.
> fix test title & timeout error

- directories/local-conformance-1_2.v2.json
Adding a config flag necessary for 1.2 conformance, supported from Finsemble 8.6.0 onwards.
@gaganahluwalia when testing this, make sure you update your seed project to latest first and reinstall the node modules so that you are running the relevant version.
Use of the flag seems to resolve all 4 issues for me:
> Update Finsemble 1.2 manifests

- directories/local-conformance-1_2.v2.json
Release candidate branch is reverting some necessary config in the FInsemble hostManifest
> Update local-conformance-1_2.v2.json to restore fdc3 1.2 compatable config

- README.md
Swaps out table of links to non-existent files for narrative with link to test specs readme
> Fix links to test specifications (after refactor/merge of the files)

- src/constants.ts
- src/test/common/fdc3.app-channels.ts
- src/test/common/fdc3.user-channels.ts
resolves #241 
Add short waits to basic channel tests to allow context to arrive on lower-performance machines, which may be more prone to race conditions.
> Make tests more robust on lower performance machines

- directories/local-conformance-2_0.v2.json
- options/glue/v2.0/glue42/core-plus/startCorePlusRunner.js
- options/glue/v2.0/glue42/startRunner.js
- src/mock/v2.0/basic.ts
- src/mock/v2.0/intent-a.ts
- src/mock/v2.0/intent-b.ts
- src/mock/v2.0/intent-c.ts
- src/mock/v2.0/intent-e.ts
- src/mock/v2.0/intent-f.ts
- src/mock/v2.0/intent-j.ts
- src/mock/v2.0/intent-k.ts
- src/mock/v2.0/metadata.ts
- src/mock/v2.0/open-a.ts
- src/test/common/fdc3.basic.ts
- src/test/common/fdc3.open.ts
- src/test/v2.0/advanced/fdc3.findInstances.ts
- src/test/v2.0/advanced/fdc3.getInfo.ts
- src/test/v2.0/advanced/fdc3.raiseIntent-Result.ts
- src/test/v2.0/advanced/fdc3.raiseIntent.ts
- src/test/v2.0/support/intent-support-2.0.ts
- src/test/v2.0/support/open-support-2.0.ts
- src/test/v2.1/advanced/fdc3.open.ts
The intent tests which test channel results contain a race condition that often fails in a local run and always fails on a lower-performance CI machine. There are also a number of minor issues the app definitions that should be fixed (but don't cause failures, but might in some implementations if they require the appD record to be accurate) and excessive use of magic strings rather than string constants.
This PR: 
- Corrects the Intent Channel result tests, 
- Ensures Errors are thrown on timeouts rather than strings,
- Makes sure the intent tests use constants for control message types, rather than magic strings.
- Removes` bTestingIntent` from the Intent B app's appD definition as it is not used and no listener is added for it by the v2.0 test app.
- Adds `ConformanceListener` to …
> Fix intent channel result tests, a couple of app definitions and use of magic strings

- directories/local-conformance-2_0.v2.json
Adding the respective number to the displayName of sharedTestingIntent1 and sharedTestingIntent2 so that Intent Resolvers using the displayName can separate the two...
> Update DisplayName for Shared Testing Intents

- src/constants.ts
- src/test/v2.0/advanced/fdc3.findIntent.ts
- src/test/v2.0/advanced/fdc3.raiseIntent.ts
- src/test/v2.0/manual/fdc3.manual.ts
- src/test/v2.0/testSuite.ts
1. v2.0/advanced/fdc3.findIntent.ts: Fixed the displayName for Intent.sharedTestingIntent2 and Intent.sharedTestingIntent1 to 'Shared Testing Intent 2' and 'Shared Testing Intent 1', respectively.
2. v2.0/advanced/fdc3.raiseIntent.ts: Suggesting adding a brief delay of ~300ms at line 118 after the context listeners are added, and before broadcasting the context to private channel, to ensure the Desktop Agent has sufficient time to initialize everything properly.
3. Manual Tests: The TestTimeout of 20,000ms seemed insufficient for fdc3ResolveAmbiguousContextTargetMultiInstance_2_0 and fdc3ResolveAmbiguousIntentTargetMultiInstance_2_0. These tests open four applications, then trigger a UI resolver app, which waits for user input before resolving. Given the dependency on user action, …
> Bugfixes: FDC3 2.0 Conformance OSFF 2024
